name: Create your wishlist
description: Hhhehehehe
title: "Christmas wish list"
label: "wishlist"
body:
  - type:
    attributes: markdown
      value: |
        Dear Santa
  - type: input
    attributes:
      placeholder: "Hello"
