name: Create your wishlist
description: 
title: "Christmas wish list"
labels: "wishlist"
body:
- type: markdown
  attributes:
    value: |
        Dear Santa,
        
        All I want for Christmas is !

        John
