name: Create your wishlist
description: 
title: "Christmas wish list"
label: "wishlist"
body:
  - type: markdown
    attributes:
      value: |
        Dear Santa,
        
        All I want for Christmas is <!-- What's your wish? -->!

        John
