name: "Dear Santa"
on:
  issue_comment:
  issues:
    types: [labeled]

jobs:
  dear-santa:
    runs-on: ubuntu-latest
    steps:
      - uses: imjohnbo/dear-santa-action@v1.0.5
        with:
          label: wishlist
