on:
  issues:
    types: [labeled]

jobs:
  dear-santa:
    runs-on: ubuntu-latest
    steps:
      - name: Dear Santa Action
        uses: imjohnbo/dear-santa-action@v1.0.5
        with:
          label: wishlist
